import React from 'react';
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
  };
const page = () => {
    return (
        <div>
            <h1>home</h1>
        </div>
    );
};

export default page;